const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { initCommittedGitRepo, makeBenchmarkResult, runNodeJson, runNodeResult, withTempDir, writeBenchmarkRun, writeFiles } = require('./test-helpers.js');

const ROOT = path.resolve(__dirname, '..');
const BENCHMARK_SUITE = path.join(ROOT, 'scripts', 'benchmark-suite.js');
const RELEASE_AUDIT = path.join(ROOT, 'scripts', 'release-audit-export.js');
const RELEASE_EVIDENCE = path.join(ROOT, 'scripts', 'release-evidence.js');
const RELEASE_OVERRIDE = path.join(ROOT, 'scripts', 'release-override.js');
const RELEASE_REHEARSAL = path.join(ROOT, 'scripts', 'release-rehearsal.js');
const RELEASE_CHECK = path.join(ROOT, 'scripts', 'release-check.js');
function writeHealthyRuns(dir) { for (let i = 1; i <= 8; i += 1) { writeBenchmarkRun(dir, { run_id: `run-${i}`, completed_at: `2026-04-${String(i).padStart(2, '0')}T10:00:00.000Z`, results: [makeBenchmarkResult({ passed: true, task_success: true, failed_count: 0, review_verdict: 'ACCEPT' })] }); } }

test('release-check recommends canonical benchmark baseline naming for project profile', () => { withTempDir((dir) => { writeFiles(dir, { 'package.json': JSON.stringify({ name: 'fixture-node', version: '1.0.0', scripts: { test: 'node --test' }, dependencies: { express: '^4.0.0' } }, null, 2), '.gitignore': 'node_modules\n', 'src/index.js': 'module.exports = {}\n' }); initCommittedGitRepo(dir); writeHealthyRuns(dir); runNodeJson(BENCHMARK_SUITE, ['baseline', '--profile', 'node-api', '--policy', 'production', '--latest', '--json'], { cwd: dir }); runNodeJson(BENCHMARK_SUITE, ['approve', '--profile', 'node-api', '--policy', 'production', '--json'], { cwd: dir }); }, (dir) => { const result = runNodeResult(RELEASE_CHECK, ['--policy', 'production', '--json'], { cwd: dir }); const report = JSON.parse(result.stdout); assert.equal(report.benchmark_baseline_naming.recommended_name, 'release.node-api.production'); assert.equal(report.benchmark_baseline_naming.selected_name, 'release.node-api.production'); assert.equal(report.benchmark_baseline.name, 'release.node-api.production'); assert.equal(report.baseline_approval.ready, true); }); });

test('release-evidence reports high override pressure when overrides are repeated', () => { withTempDir((dir) => { writeFiles(dir, { 'package.json': JSON.stringify({ name: 'fixture-node', version: '1.0.0', scripts: { test: 'node --test' } }, null, 2), '.gitignore': 'node_modules\n', 'src/index.js': 'module.exports = {}\n' }); initCommittedGitRepo(dir); writeHealthyRuns(dir); runNodeJson(BENCHMARK_SUITE, ['baseline', '--latest', '--json'], { cwd: dir }); runNodeJson(BENCHMARK_SUITE, ['approve', '--json'], { cwd: dir }); const checks = 'benchmark.latest_comparison,benchmark.scope_coverage'; for (let i = 0; i < 3; i += 1) { const requested = runNodeJson(RELEASE_OVERRIDE, ['request', '--policy', 'standard', '--reason', `temporary solo override reason number ${i} for release stabilization`, '--checks', checks, '--expires-at', '2026-04-13T12:00:00.000Z', '--now', '2026-04-13T00:00:00.000Z', '--json'], { cwd: dir }); runNodeJson(RELEASE_OVERRIDE, ['approve', '--id', requested.override_id, '--by', 'qa-lead', '--json'], { cwd: dir }); } }, (dir) => { const report = runNodeJson(RELEASE_EVIDENCE, ['--policy', 'standard', '--json'], { cwd: dir }); assert.equal(report.summary.override_pressure.status, 'high'); assert.equal(report.summary.override_pressure.last_30_days_count, 3); assert.equal(report.summary.override_pressure.high_frequency, true); assert.ok(report.summary.override_pressure.repeated_checks_last_30_days.some((item) => item.check === 'benchmark.latest_comparison')); }); });

test('release audit export can emit a stable directory bundle', () => { withTempDir((dir) => { writeFiles(dir, { 'package.json': JSON.stringify({ name: 'fixture-node', version: '1.0.0', scripts: { test: 'node --test' }, dependencies: { express: '^4.0.0' } }, null, 2), '.gitignore': 'node_modules\n', 'src/index.js': 'module.exports = {}\n' }); initCommittedGitRepo(dir); writeHealthyRuns(dir); runNodeJson(BENCHMARK_SUITE, ['baseline', '--profile', 'node-api', '--policy', 'production', '--latest', '--json'], { cwd: dir }); runNodeJson(BENCHMARK_SUITE, ['approve', '--profile', 'node-api', '--policy', 'production', '--json'], { cwd: dir }); execFileSync('git', ['add', ' .'.trim()], { cwd: dir, encoding: 'utf8' }); execFileSync('git', ['commit', '-qm', 'record release audit fixtures'], { cwd: dir, encoding: 'utf8', env: { ...process.env, GIT_AUTHOR_NAME: 'tester', GIT_AUTHOR_EMAIL: 'tester@example.com', GIT_COMMITTER_NAME: 'tester', GIT_COMMITTER_EMAIL: 'tester@example.com' } }); runNodeResult(RELEASE_REHEARSAL, ['--policy', 'production', '--json'], { cwd: dir }); }, (dir) => { const out = path.join(dir, 'audit-bundle'); const result = runNodeJson(RELEASE_AUDIT, ['--policy', 'production', '--out', out, '--dir', '--json'], { cwd: dir }); assert.equal(result.type, 'directory'); const manifest = JSON.parse(fs.readFileSync(path.join(out, 'manifest.json'), 'utf8')); const bundle = JSON.parse(fs.readFileSync(path.join(out, 'bundle.json'), 'utf8')); assert.equal(manifest.baseline_name, 'release.node-api.production'); assert.equal(bundle.manifest.release_decision, bundle.evidence.summary.release_decision); for (const name of ['README.md', 'summary.json', 'evidence.json', 'release-check.json', 'rehearsal.json', 'baseline.json', 'approval.json', 'overrides.json', 'observability-events.json']) assert.equal(fs.existsSync(path.join(out, name)), true, name); const summary = JSON.parse(fs.readFileSync(path.join(out, 'summary.json'), 'utf8')); assert.equal(summary.release_conclusion.release_decision, bundle.release_conclusion.release_decision); }); });
