# {{subject}} integration note

Generated by `generate-node-feature`.

## Project memory snapshot

- Coding style: `{{project.coding_style}}`
- API style: `{{project.api_style}}`
- Validation: `{{project.validation_lib}}`
- ORM: `{{project.orm}}`
- Auth: `{{project.auth_strategy}}`
- Errors: `{{project.error_pattern}}`
- Preferred feature shape: `{{project.preferred_feature_shape}}`
- Generation safe mode: `{{project.generation_safe_mode}}`
- Import repair bias: `{{project.import_repair_bias}}`
- Verify bias: `{{project.verify_bias}}`
- Implementation style: `{{project.implementation_style}}`
- Shape strategy: `{{project.shape_strategy}}`
- Route style: `{{project.route_style}}`
- Auth mode: `{{project.auth_mode}}`
- Shared error integration: `{{project.shared_error_integration}}`
- Global error handler integration: `{{project.global_error_handler_integration}}`
- Preferred test command: `{{project.preferred_test_command}}`

## Planning feedback

- Plan mode: `{{project.plan_mode}}`
- Verify preference: `{{project.verify_preference}}`
- Planned test module: `{{project.plan_with_test}}`
- Planned docs module: `{{project.plan_with_docs}}`
- Planned repository module: `{{project.plan_with_repository}}`
- Plan adjustment reasons: `{{project.plan_adjustment_reasons}}`
- Enabled modules: `{{enabled_modules}}`

## Files

{{generated_files_list}}

## Dependency order

{{integration_dependencies}}

## Follow-up

1. Mount `register{{pascal_name}}Routes` from your server bootstrap.
2. Replace repository placeholder logic with real persistence.
3. Tighten payload typing and request validation.

- App entrypoint integration: `{{project.app_entrypoint_integration}}`
- Preferred CI test command: `{{project.preferred_test_command_ci}}`
- Preferred watch test command: `{{project.preferred_test_command_watch}}`
- Preferred coverage test command: `{{project.preferred_test_command_coverage}}`
- Preferred test runner profile: `{{project.preferred_test_runner_profile}}`
