const fs = require('fs');
const path = require('path');
const { toCamelCase, toKebabCase, writeFile } = require('./common.js');

/** @typedef {{ name?: string, summary?: string }} CommandScaffoldOptions */

/** @param {string} rootDir @param {CommandScaffoldOptions} [options] */
function createCommandScaffold(rootDir, options = {}) {
  const commandName = toKebabCase(options.name);
  if (!commandName) throw new Error('command name is required');
  const functionName = `build${toCamelCase(commandName).replace(/^([a-z])/, (_, ch) => ch.toUpperCase())}Report`;
  const scriptPath = path.join(rootDir, 'scripts', `${commandName}.js`);
  const corePath = path.join(rootDir, 'src', 'core', `${commandName}.js`);
  const testPath = path.join(rootDir, 'tests', `${commandName}.test.js`);
  if (fs.existsSync(scriptPath) || fs.existsSync(corePath)) throw new Error(`command already exists: ${commandName}`);
  const summary = String(options.summary || `${commandName} command`).trim();
  const coreBody = `/**
 * @typedef {{ ok: boolean, command: string, summary: string }} ${functionName}Result
 */

/**
 * @param {{ rootDir?: string }} [options]
 * @returns {${functionName}Result}
 */
function ${functionName}(options = {}) {
  return {
    ok: true,
    command: '${commandName}',
    summary: ${JSON.stringify(summary)},
  };
}

module.exports = { ${functionName} };
`;
  const scriptBody = `#!/usr/bin/env node
const { ${functionName} } = require('../../src/core/${commandName}.js');

function main() {
  const args = process.argv.slice(2);
  const wantsJson = args.includes('--json');
  const result = ${functionName}({ rootDir: process.cwd() });
  if (wantsJson) {
    process.stdout.write(\`${'${'}JSON.stringify(result, null, 2){'}'}\n\`);
    return;
  }
  process.stdout.write(\`[${commandName}] ${'${'}result.summary{'}'}\n\`);
}

main();
`;
  const testBody = `const test = require('node:test');
const assert = require('node:assert/strict');
const { ${functionName} } = require('../../src/core/${commandName}.js');

test('${commandName} scaffold returns stable result shape', () => {
  const result = ${functionName}();
  assert.equal(result.ok, true);
  assert.equal(result.command, '${commandName}');
});
`;
  const docBody = `# ${commandName}

- Summary: ${summary}
- JSON support: yes
- Generated by: scripts/create-command.js
`;
  const files = [
    writeFile(rootDir, path.relative(rootDir, corePath), coreBody),
    writeFile(rootDir, path.relative(rootDir, scriptPath), scriptBody),
    writeFile(rootDir, path.relative(rootDir, testPath), testBody),
    writeFile(rootDir, path.join('docs', 'commands', `${commandName}.md`), docBody),
  ];
  fs.chmodSync(scriptPath, 0o755);
  return { command: commandName, files };
}

module.exports = { createCommandScaffold };
