name: semgrep

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit
